### ISSUE TITLE
PHP Error at index.php: "Warning: Undefined array key "power" in C:\server\htdocs\sebtest\includes\functions.inc.php on line 2098"

### ISSUE THREAD

**Issue by Apilonius64** [ItsSebis/sebsurf#3]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/103268036/162946854-f03d8f44-0335-46ac-b6ea-ccbeffc98284.png">
When I use the default setup assistent to set up my sebsurf installation I get the following Error: "Warning: Undefined array key "power" in C:\server\htdocs\sebtest\includes\functions.inc.php on line 2098".

**Comment by ItsSebis** [comment]
I forgot to update the setup functions for the update. Thanks
